module-template: ! 'module MODULE_NAME where

'
extensions: {}
environment: null
cabal-file: project.cabal
modules:
  TermSpec:
    filename: src/TermSpec.hs
  Term:
    filename: src/Term.hs
  Core:
    filename: src/Core.hs
  CoreSpec:
    filename: src/CoreSpec.hs
version: 1
ghc-args: []
