module-template: ! 'module MODULE_NAME where

'
extensions: {}
environment: ghc-7.4.2-stable-13.09
cabal-file: project.cabal
modules:
  Pipe:
    filename: src/Pipe.hs
  AssocViolation:
    filename: src/AssocViolation.hs
version: 1
ghc-args: []
